### ISSUE TITLE
Bug in readme!

### ISSUE THREAD

**Issue by k0dep** [uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu/uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu#3] opened 2019-12-18 19:26 UTC
<img width="1052" alt="Screenshot_1" src="https://user-images.githubusercontent.com/7011790/71116507-570e3e00-21e5-11ea-82a9-da5ef7a47d56.png">

**Comment by NotNite** [comment] 2019-12-18 19:32
I can't seem to reproduce this, sadly. What browser are you using?

**Comment by Cynosphere** [comment] 2019-12-18 19:41
Can replicate on Vivaldi.

**Comment by NotNite** [comment] 2019-12-18 19:44
![image](https://user-images.githubusercontent.com/44414597/71117782-cca5ea00-21a4-11ea-879a-1faf2fa531a4.png)
This is quite strange. I can replicate it in incognito mode using Vivaldi, but not when logged in. The number of "u"s shifted off to the side does not correlate with @k0dep's screenshot.

**Comment by NotNite** [comment] 2019-12-18 19:46
@Cynosphere, do you have a screenshot of your replication?

**Comment by Cynosphere** [comment] 2019-12-18 21:32
![random sticking out u](https://totallynotavir.us/i/ddk48j8d.png)

**Comment by alexmodrono** [comment] 2019-12-19 13:15
I can reproduce it with Brave. However, this seems to be a GitHub bug, not a problem with the README.


<img width="1920" alt="Screenshot 2019-12-19 at 14 12 42" src="https://user-images.githubusercontent.com/28487357/71176236-b3b33c80-2269-11ea-8bf6-dc7f202123e2.png">

**Comment by jamacon36** [comment] 2019-12-19 17:26
Of interest - Chrome 79.0.3945.79:
![Screen Shot 2019-12-19 at 12 25 22 PM](https://user-images.githubusercontent.com/4700339/71194863-bbb7b000-225a-11ea-8342-eaff03bba14c.png)

**Comment by NotNite** [comment] 2019-12-19 19:40
Yeah, I sadly don't think I can fix this. This seems to be a problem with GitHub's UI, since it renders fine on my machine locally.

After all, one of this project's goals IS to break GitHub's UI.

Closing now since I can't fix it.

**Closed as completed by NotNite** 2019-12-19 19:40 UTC
Labels: repo
